[package]
name = "obamify"
version = "0.3.0"
authors = ["Spu7Nix"]
edition = "2024"
include = ["LICENSE-MIT", "**/*.rs", "Cargo.toml"]
rust-version = "1.85"

[package.metadata.docs.rs]
all-features = true
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
log = "0.4.27"
wgpu = { version = "25.0", features = ["wgsl", "vulkan", "dx12", "metal"] }
bytemuck = { version = "1.16", features = ["derive"] }
image = { version = "0.25.6", features = ["serde"] }

palette = "0.7.6"
pathfinding = "4.13.0"
indexmap = "2.11.0"

frand = "0.10.1"
uuid = { version = "1.18.1", features = ["v4", "serde"] }

gif = "0.13.3"
futures-intrusive = "0.5.0"
pollster = "0.4.0"
color_quant = "1.1.0"

serde = { version = "1.0.219", features = ["derive"] }

# CLI 需要的額外依賴
tokio = { version = "1", features = ["full"] }

# native:
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
env_logger = "0.11.8"

[profile.release]
opt-level = 3

[profile.dev.package."*"]
opt-level = 2
